/** @typedef {import("../../shared/api/classificationStandardContracts").ClassificationStandardDetail} ClassificationStandardDetail */
/** @typedef {import("../../shared/api/classificationStandardContracts").ClassificationStandardDraft} ClassificationStandardDraft */
/** @typedef {import("../../shared/api/classificationStandardContracts").ClassificationStandardEditableContent} ClassificationStandardEditableContent */
/** @typedef {import("../../shared/api/classificationStandardContracts").ClassificationStandardValidationIssue} ClassificationStandardValidationIssue */
/** @typedef {import("../../shared/api/classificationStandardContracts").ClassificationStandardValidationRunDetail} ClassificationStandardValidationRunDetail */
/** @typedef {import("../../shared/api/classificationStandardContracts").ClassificationStandardValidationRunSummary} ClassificationStandardValidationRunSummary */
/** @typedef {import("../../shared/api/classificationStandardContracts").ClassificationStandardValidationSource} ClassificationStandardValidationSource */
/** @typedef {import("../../shared/api/classificationStandardContracts").ClassificationStandardVersion} ClassificationStandardVersion */
/** @typedef {import("../../shared/api/classificationStandardContracts").ClassificationStandardReviewRole} ClassificationStandardReviewRole */
/** @typedef {import("../../shared/api/classificationStandardContracts").ReadableRecognitionProfile} ReadableRecognitionProfile */
/** @typedef {import("../../shared/api/classificationStandardContracts").ValidationSampleSize} ValidationSampleSize */
/** @typedef {import("./classificationStandardContent").ClassificationStandardFieldErrors} ClassificationStandardFieldErrors */
/** @typedef {{initiallyEditing: boolean, versions: ClassificationStandardVersion[], notify: (message: string, tone?: string) => void, onDelete: () => void, onRestore: (version: ClassificationStandardVersion) => void, savedContent: ClassificationStandardEditableContent | null, focusLabelCode?: string, isNew: boolean, detail: ClassificationStandardDetail | null, draft: ClassificationStandardDraft | null, content: ClassificationStandardEditableContent, changeReason: string, busy: string, dirty: boolean, validationSources: ClassificationStandardValidationSource[], validationRuns: ClassificationStandardValidationRunSummary[], selectedValidation: ClassificationStandardValidationRunDetail | null, validationSourceId: string, validationSampleSize: ValidationSampleSize, fieldErrors: Partial<ClassificationStandardFieldErrors>, validationAttempt: number, onContentChange: (content: ClassificationStandardEditableContent, field?: string) => void, onReasonChange: (reason: string) => void, onSave: () => void | Promise<void>, onPublish: (validationRunId?: string | null) => void | Promise<void>, onBack: () => void, onValidationSourceChange: (sourceId: string) => void, onValidationSampleSizeChange: (size: ValidationSampleSize) => void, onValidationRun: (file: File | null, comparisonType?: string) => void | Promise<void>, onImport: (event: import("react").ChangeEvent<HTMLInputElement>) => void | Promise<void>, onPrepareExcel: () => Promise<ClassificationStandardDraft>, onApplyExcel: (content: ClassificationStandardEditableContent, filename: string) => void, onValidationSelect: (runId: string) => void | Promise<void>}} ClassificationStandardWorkspaceProps */

/** @typedef { ClassificationStandardWorkspaceProps & ReturnType<typeof import("./useStandardWorkspace").useStandardWorkspace>} StandardWorkspaceContext */
export {};
